import { registerSW } from 'virtual:pwa-register'

// Registers the service worker generated by vite-plugin-pwa. This is the
// foundation for installability (Android "Install app" prompt + iOS standalone)
// and offline shell caching.
//
// DEFERRED (no rework needed to add later): push notifications and icon badges
// layer onto this same service worker.
//   - Push:  add a custom SW handler for `push` / `notificationclick`, request
//            Notification permission, subscribe with VAPID keys, and send from a
//            Supabase Edge Function. iOS requires the PWA be installed (16.4+).
//   - Badge: `navigator.setAppBadge(count)` / `clearAppBadge()` once installed.
export function registerPwa(): void {
  if (import.meta.env.DEV) return

  const updateSW = registerSW({
    onNeedRefresh() {
      showReloadBanner(() => updateSW(true))
    },
  })
}

// Minimal self-contained banner — no generic toast component exists in the app,
// so this avoids pulling SW lifecycle into the React tree.
function showReloadBanner(onReload: () => void): void {
  if (document.getElementById('pwa-reload-banner')) return

  const banner = document.createElement('div')
  banner.id = 'pwa-reload-banner'
  banner.setAttribute('role', 'status')
  banner.style.cssText = [
    'position:fixed',
    'left:50%',
    'bottom:max(16px,env(safe-area-inset-bottom))',
    'transform:translateX(-50%)',
    'z-index:2147483647',
    'display:flex',
    'align-items:center',
    'gap:12px',
    'padding:12px 16px',
    'border-radius:14px',
    'background:#1C1828',
    'color:#F4F1FA',
    'font:500 14px/1.2 "DM Sans",system-ui,sans-serif',
    'box-shadow:0 8px 28px rgba(0,0,0,0.45)',
    'border:1px solid rgba(255,255,255,0.08)',
  ].join(';')

  const label = document.createElement('span')
  label.textContent = 'New version available'

  const button = document.createElement('button')
  button.type = 'button'
  button.textContent = 'Reload'
  button.style.cssText = [
    'appearance:none',
    'border:0',
    'cursor:pointer',
    'padding:8px 14px',
    'border-radius:10px',
    'background:#7C5CFF',
    'color:#fff',
    'font:600 14px/1 "DM Sans",system-ui,sans-serif',
  ].join(';')
  button.addEventListener('click', () => {
    button.disabled = true
    button.textContent = 'Reloading…'
    onReload()
  })

  banner.append(label, button)
  document.body.appendChild(banner)
}
